version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${PROJECT_NAME}
      MARIADB_USER: ${DB_SLAVE_USER_NAME}
      MARIADB_PASSWORD: ${DB_SLAVE_USER_PASSWORD}
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
      - ~/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u${DB_SLAVE_USER_NAME} -p${DB_SLAVE_USER_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis-container
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    networks:
      - app-network

  app:
    image: $DOCKER_HUB_USER_NAME/${PROJECT_NAME}:${PROJECT_VERSION}
    container_name: ${PROJECT_NAME}
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      EC2_IP_FOR_BSHERPA: ${EC2_IP_FOR_BSHERPA}
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_VERSION: ${PROJECT_VERSION}
      SPRING_DATASOURCE_MASTER_URL: jdbc:mariadb://${BSHERPA_AWS_RDS_ENDPOINT}:3306/${PROJECT_NAME}
      SPRING_DATASOURCE_MASTER_USERNAME: ${DB_MASTER_USER_NAME}
      SPRING_DATASOURCE_MASTER_PASSWORD: ${DB_MASTER_USER_PASSWORD}
      SPRING_DATASOURCE_SLAVE_URL: jdbc:mariadb://mariadb-container:3306/${PROJECT_NAME}
      SPRING_DATASOURCE_SLAVE_USERNAME: ${DB_SLAVE_USER_NAME}
      SPRING_DATASOURCE_SLAVE_PASSWORD: ${DB_SLAVE_USER_PASSWORD}
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}
      BSHERPA_JWT_SECRET_KEY: ${BSHERPA_JWT_SECRET_KEY}
      BSHERPA_ACCESS_TOKEN_EXPIRATION_TIME: ${BSHERPA_ACCESS_TOKEN_EXPIRATION_TIME}
      BSHERPA_REFRESH_TOKEN_EXPIRATION_TIME: ${BSHERPA_REFRESH_TOKEN_EXPIRATION_TIME}
      SSL_KEY_STORE_PASSWORD: ${SSL_KEY_STORE_PASSWORD}
      BSHERPA_RDS_ENDPOINT: ${BSHERPA_RDS_ENDPOINT}
      BSHERPA_S3_ACCESS_KEY: ${BSHERPA_S3_ACCESS_KEY}
      BSHERPA_S3_SECRET_KEY: ${BSHERPA_S3_SECRET_KEY}
      BSHERPA_S3_BUCKET_NAME: ${BSHERPA_S3_BUCKET_NAME}
      TSHERPA_API_URL: ${TSHERPA_API_URL}
      TSHERPA_API_GET_ITEMS_URL: ${TSHERPA_API_GET_ITEMS_URL}
      TSHERPA_API_GET_ITEM_IMAGES_URL: ${TSHERPA_API_GET_ITEM_IMAGES_URL}
      TSHERPA_API_GET_CHAPTER_ITEMS_URL: ${TSHERPA_API_GET_CHAPTER_ITEMS_URL}
      TSHERPA_API_GET_CHAPTER_ITEM_IMAGES_URL: ${TSHERPA_API_GET_CHAPTER_ITEM_IMAGES_URL}
      TSHERPA_API_GET_EXAM_ITEMS_URL: ${TSHERPA_API_GET_EXAM_ITEMS_URL}
      TSHERPA_API_GET_EXAM_ITEM_IMAGES_URL: ${TSHERPA_API_GET_EXAM_ITEM_IMAGES_URL}
      TSHERPA_API_GET_SIMILAR_ITEMS_URL: ${TSHERPA_API_GET_SIMILAR_ITEMS_URL}
      TSHERPA_API_GET_SIMILAR_ITEM_IMAGES_URL: ${TSHERPA_API_GET_SIMILAR_ITEM_IMAGES_URL}
      TSHERPA_API_GET_ITEM_COUNTS_URL: ${TSHERPA_API_GET_ITEM_COUNTS_URL}
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    ports:
      - "443:443"
    networks:
      - app-network
    volumes:
      - /home/ubuntu/keystore.p12:/app/keystore.p12

networks:
  app-network:
    driver: bridge
  es-bridge:
    driver: bridge

volumes:
  db_data:
