server:
  url: ${BSHERPA_IP}
  port: 443
  ssl:
    key-store: file:/app/keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    keyStoreType: PKCS12
    keyAlias: tomcat
spring:
  application:
    name: bsherpa
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    view:
      prefix: /
      suffix: .html
  datasource:
    master:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://${BSHERPA_RDS_ENDPOINT}:3306/${PROJECT_NAME}?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
      username: ${DB_MASTER_USER_NAME}
      password: ${DB_MASTER_USER_PASSWORD}
    slave:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://mariadb-container:3306/${PROJECT_NAME}?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
      username: ${DB_SLAVE_USER_NAME}
      password: ${DB_SLAVE_USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
          format_sql: true
    show-sql: true
    database: mysql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false
  redis:
    host: redis-container
    port: 6379
    password: ${REDIS_PASSWORD}
logging:
  config: classpath:logback-spring.xml
jwt:
  secret:
    key: ${BSHERPA_JWT_SECRET_KEY}
  access-token:
    expiration-time: ${BSHERPA_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token:
    expiration-time: ${BSHERPA_REFRESH_TOKEN_EXPIRATION_TIME}
cloud:
  aws:
    credentials:
      access-key: ${BSHERPA_S3_ACCESS_KEY}
      secret-key: ${BSHERPA_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket-name: ${BSHERPA_S3_BUCKET_NAME}
tsherpa:
  api:
    url: ${TSHERPA_API_URL}
    get-items:
      url: ${TSHERPA_API_GET_ITEMS_URL}
    get-item-images:
      url: ${TSHERPA_API_GET_ITEM_IMAGES_URL}
    get-chapter-items:
      url: ${TSHERPA_API_GET_CHAPTER_ITEMS_URL}
    get-chapter-item-images:
      url: ${TSHERPA_API_GET_CHAPTER_ITEM_IMAGES_URL}
    get-exam-items:
      url: ${TSHERPA_API_GET_EXAM_ITEMS_URL}
    get-exam-item-images:
      url: ${TSHERPA_API_GET_EXAM_ITEM_IMAGES_URL}
    get-similar-items:
      url: ${TSHERPA_API_GET_SIMILAR_ITEMS_URL}
    get-similar-item-images:
      url: ${TSHERPA_API_GET_SIMILAR_ITEM_IMAGES_URL}
    get-item-counts:
      url: ${TSHERPA_API_GET_ITEM_COUNTS_URL}
    get-chapters:
      url: ${TSHERPA_API_GET_CHAPTERS_URL}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
