server:
  url: ${BSHERPA_IP}
  port: 443
  ssl:
    key-store: file:/app/keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    keyStoreType: PKCS12
    keyAlias: tomcat
spring:
  application:
    name: bsherpa
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    view:
      prefix: /
      suffix: .html
  datasource:
    master:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://${BSHERPA_AWS_RDS_ENDPOINT}:3306/${PROJECT_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
      username: ${DB_MASTER_USER_NAME}
      password: ${DB_MASTER_USER_PASSWORD}
    slave:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://mariadb-container:3306/${PROJECT_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
      username: ${DB_SLAVE_USER_NAME}
      password: ${DB_SLAVE_USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
          format_sql: true
    show-sql: true
    database: mysql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false
  redis:
    host: redis-container
    port: 6379
    password: ${REDIS_PASSWORD}
logging:
  config: classpath:logback-spring.xml
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
